### ISSUE TITLE
wicd-curses crashed when pressed arrow keys after refreshing the list.

### ISSUE THREAD

**Issue by fkztw** [fkztw/wicd#1]
```
Traceback (most recent call last):(IP: 192.168.2.3)                                                                                     
  File "/usr/share/wicd/curses/wicd-curses.py", line 1149, in call_update_ui
    self.update_ui(True)
  File "/usr/share/wicd/curses/wicd-curses.py", line 97, in wrapper
    return func(*args, **kargs)
  File "/usr/share/wicd/curses/wicd-curses.py", line 1162, in update_ui
    self.handle_keys(input_data)
  File "/usr/share/wicd/curses/wicd-curses.py", line 1131, in handle_keys
    k = self.frame.keypress(self.size, k)
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python2.7/site-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/share/wicd/curses/wicd-curses.py", line 474, in keypress
    key = ComboBox.keypress(self, size, key)
  File "/usr/share/wicd/curses/curses_misc.py", line 497, in keypress
    return self._w.keypress(size, key)
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
AttributeError: 'Text' object has no attribute 'keypress'
```

**Comment by fkztw** [comment]
https://github.com/johnboiles/wicd/commit/c6f801ab300901002bb5c88bbf4224b42605cdd0
This fork fixed the bug.
